# 1. REQUIRED: Para gumana sa Railway Port
server.port=${PORT:8080}

# 2. Database Config (Gamit ang Variable na ginawa natin kanina)
spring.datasource.url=jdbc:mysql://mysql-6e315ed-acceptable-harmony.g.aivencloud.com:15683/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${APP_DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Hibernate Settings (Para sa Database tables)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 4. FIX PARA SA .HTM FILES MO
spring.thymeleaf.suffix=.htm
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.mode=HTML