spring.application.name=registrar-portal

# ==========================================
# ?? AIVEN CLOUD DATABASE CONNECTION
# ==========================================
# Pinalitan na natin ang localhost ng Aiven URL
spring.datasource.url=jdbc:mysql://mysql-6e315ed-gremioemmanueljustine-7a16.h.aivencloud.com:11484/defaultdb?ssl-mode=REQUIRED

# Ang User mo sa Aiven
spring.datasource.username=avnadmin

# ?? ILAGAY MO ANG PASSWORD DITO (Yung galing sa Website)
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# JPA Settings (Para automatic gumawa ng tables)
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# File Upload Settings
# ==========================================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

server.port=8080